route:
  receiver: alert-log
  group_by: ["alertname", "environment"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: alert-log
    webhook_configs:
      - url: http://alert-receiver:5001/alert
        send_resolved: true
